### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [Konstantin-Okhlynin/RegExp#1]
Отличная работа, нужно сделать не большие исправления, что бы была корректная валидация примеров ниже.

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Надо исправить**
- `y@ya.ru` - имя ящика может состоять из одного символа
- *http://mysite.com/path#* - Необходимо позволить пользователю вводить путь со знаком # в конце и без него.

**Можно лучше**
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий. В вашем проекте нет лишних файлов, но можно добавить gitignore что бы лишние файлы(картинки или системных файлы) не попали сюда. Подробный ответ зачем это нужно [по ссылке](https://ru.stackoverflow.com/questions/546520/%D0%94%D0%BB%D1%8F-%D1%87%D0%B5%D0%B3%D0%BE-%D0%BD%D1%83%D0%B6%D0%B5%D0%BD-%D1%84%D0%B0%D0%B9%D0%BB-gitignore).

**Comment by talantbekov123** [comment]
Отличная работа, комментарии исправлены! Похвально! Принимаю.

**Comment by KonstantinOkhlynin** [comment]
> Отличная работа, комментарии исправлены! Похвально! Принимаю.

Спасибо)
